spring.application.name=TrabajosSpring
server.port=8112

# H2 Database
#spring.datasource.url=jdbc:h2:mem:clubesdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/clubes_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123098
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Data SQL
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
